staging:
 password: #PRIVATE_APP_PASSWORD
 theme_id: "194828164"
 store: indira-active.myshopify.com
 ignore_files:
   - .git/
   - .gitignore
   - .circleci/
   - README.md
   - additional/
 timeout: 60s
master:
 password: #PRIVATE_APP_PASSWORD
 theme_id: "194349508"
 store: indira-active.myshopify.com
 ignore_files:
 - ".git/"
 - ".gitignore"
 - .circleci/  
 - README.md
 - additional/
 timeout: 60s
 readonly: true
testing:
 password: #PRIVATE_APP_PASSWORD
 theme_id: "461307929"
 store: indira-testing.myshopify.com
 ignore_files:
 - ".git/"
 - ".gitignore"
 - .circleci/  
 - README.md
 - additional/
 timeout: 60s
