staging:
 password: 371ea5d17111812343c1e6a72e1b1368
 theme_id: "194828164"
 store: indira-active.myshopify.com
 ignore_files:
   - .git/
   - .gitignore
   - .circleci/
   - README.md
   - additional/
 timeout: 60s
 readonly: true
master:
 password: 371ea5d17111812343c1e6a72e1b1368
 theme_id: "194349508"
 store: indira-active.myshopify.com
 ignore_files:
 - ".git/"
 - ".gitignore"
 - .circleci/  
 - README.md
 - additional/
 timeout: 60s

 